fix: update add dev tag script to check for java version

diff --git a/utils/addDevTag b/utils/addDevTag
--- a/utils/addDevTag
+++ b/utils/addDevTag
@@ -5,6 +5,17 @@ if [[ $(git log origin/master ^HEAD) ]]; then
     exit 1
 fi
 
+# Verify java version
+REQUIRED_JAVA_VERSION="15.0.1"
+JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
+
+if [[ "$JAVA_VERSION" == "$REQUIRED_JAVA_VERSION" ]]; then
+    echo "Correct Java version ($REQUIRED_JAVA_VERSION) is installed."
+else
+    echo "Error: Java version $REQUIRED_JAVA_VERSION is required, but version $JAVA_VERSION is installed."
+    exit 1
+fi
+
 # get version------------
 version=`cat build.gradle | grep -e "version =" -e "version="`
 
